spring:
  application:
    name: tasktracker

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/appdatabase?authSource=admin

springdoc:
  version: 2.5.0

  swagger-ui:
    path: /swagger-ui.html

